package com.example.inventory.sales;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

/**
 * Shapes for {@code POST /sales}, mirroring {@code docs/openapi.yaml}.
 *
 * <p>Money and quantities are {@link BigDecimal} (T7). No request carries a
 * tenant id (T1).
 */
public final class SalesDtos {

    private SalesDtos() {
    }

    /**
     * @param clientRequestId the idempotency key. Generated by the client when
     *                        the user taps save — not when the request is sent —
     *                        so a retry over a flaky link carries the same value
     *                        and the sale is recorded once.
     * @param soldAt          business time, which may be in the past. Defaults to
     *                        now. Carries an offset, and the tenant's timezone
     *                        decides which business day it lands in.
     */
    public record SaleWriteRequest(
            @NotEmpty @Valid List<SaleLineRequest> lines,
            UUID clientRequestId,
            UUID locationId,
            @Size(max = 200) String customerName,
            @Size(max = 50) String customerPhone,
            @Size(max = 50) String paymentMethod,
            @PositiveOrZero BigDecimal discountAmount,
            OffsetDateTime soldAt) {
    }

    /**
     * @param unitPrice omit to use the product's current selling price. Captured
     *                  onto the line either way, so a later price change does not
     *                  rewrite what the customer was charged.
     */
    public record SaleLineRequest(
            @NotNull UUID productId,
            @NotNull @Positive BigDecimal quantity,
            @PositiveOrZero BigDecimal unitPrice,
            @PositiveOrZero BigDecimal discountAmount) {
    }

    public record SaleLine(
            UUID productId,
            String sku,
            String name,
            BigDecimal quantity,
            BigDecimal unitPrice,
            BigDecimal discountAmount,
            BigDecimal lineTotal) {
    }

    public record SaleDetail(
            UUID id,
            String saleNumber,
            String status,
            String customerName,
            int itemCount,
            BigDecimal subtotalAmount,
            BigDecimal discountAmount,
            BigDecimal taxAmount,
            BigDecimal totalAmount,
            String paymentMethod,
            OffsetDateTime soldAt,
            UUID locationId,
            UUID createdBy,
            List<SaleLine> lines) {
    }
}
